# CircleCI 2.1 configuration file

executors:
  content-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

jobs:
  validate-content-with-AppInspect:
    executor: content-executor
    steps:
      - run:
          name: Checkout repository
          command: |
            if [ "${CIRCLE_BRANCH}" == "" ]; then
                git clone https://${GITHUB_TOKEN}@github.com/GSF1250S/devtutorial.git
            else
                git clone --branch ${CIRCLE_BRANCH} https://${GITHUB_TOKEN}@github.com/GSF1250S/devtutorial.git
            fi
      - run:
          name: Install system packages
          command: |
            sudo apt update -qq
            sudo apt install -y python3-pip
            sudo pip install --upgrade pip setuptools
            sudo pip install splunk-appinspect
      - run:
          name: Run AppInspect
          command: |
            rm -rf devtutorial/.git
            rm -rf devtutorial/.circleci
            rm -rf devtutorial/.gitignore
            splunk-appinspect inspect ./devtutorial --included-tags=cloud 

workflows:
  version: 2.1
  validate-content-workflow:
    jobs:
      - validate-content-with-AppInspect
