# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

dependencies:
  cache_directories:
    - "~/.apt-cache"
  pre:
    - sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial

apt-run: &apt-install
  name: install system packages
  command: |
    sudo apt update -qq
    sudo apt install -y python3-pip
#    sudo apt install -y python-pip
version: 2.1

executors:
  content-executor:
    docker:
      - image: cimg/base:stable
#      - image: circleci/python:latest
    working_directory: ~/repo

jobs:
  validate-content:
    executor: content-executor
    steps:
      - run:
          name: checkout repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "" ]; then
                git clone https://${GITHUB_TOKEN}@github.com/GSF1250S/devtutorial.git
            else
                git clone --branch ${CIRCLE_BRANCH} https://${GITHUB_TOKEN}@github.com/GSF1250S/devtutorial.git
            fi
#      - restore_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "devtutorial/default/app.conf" }}
      - run: *apt-install
      - run:
          name: install appinspect
          command: |
            mkdir appinspect-latest
            cd appinspect-latest
            rm -rf venv
            sudo pip install --upgrade pip setuptools
            sudo pip install virtualenv
            virtualenv --python=/usr/bin/python3 --clear venv
            source venv/bin/activate
            pip install splunk-appinspect 
      - run:
          name: run appinspect
          command: |
            rm -rf devtutorial/.git
            rm -rf devtutorial/.circleci
            rm -rf devtutorial/.gitignore
            tar -zcvf devtutorial.tar.gz devtutorial
            mkdir dist
#            cp devtutorial.tar.gz dist/
            cd appinspect-latest
            source venv/bin/activate
            splunk-appinspect inspect ../devtutorial --included-tags=cloud 
workflows:
  version: 2.1
  validate-content-workflow:
    jobs:
      - validate-content
