# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

dependencies:
  cache_directories:
    - "~/.apt-cache"
  pre:
    - sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial

apt-run: &apt-install
  name: install system packages
  command: |
    sudo apt update -qq
    sudo apt install -y python3-pip
#    sudo apt install -y python-pip
version: 2.1

executors:
  content-executor:
    docker:
      - image: cimg/base:stable
#      - image: circleci/python:latest
    working_directory: ~/repo

jobs:
  validate-content:
    executor: content-executor
    steps:
      - checkout
#      - run:
#          name: checkout repo
#          command: |
#            if [ "${CIRCLE_BRANCH}" == "" ]; then
#                git clone https://${GITHUB_TOKEN}@GSF1250S/devtutorial.git
#            else
#                git clone --branch ${CIRCLE_BRANCH} https://${GITHUB_TOKEN}@GSF1250S/devtutorial.git
#            fi
#      - restore_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "devtutorial/default/app.conf" }}
      - run: *apt-install
#      - run:
#          name: grab appinspect
#          command: |
#            mkdir appinspect-latest
#            cd appinspect-latest
#            pip install splunk-appinspect -t .            
#            pip download splunk-appinspect-2.34.0.tar.gz
#
#            pip download -d appinspect-latest splunk-appinspect-2.34.0.tar.gz
#            curl -Ls https://download.splunk.com/misc/appinspect/splunk-appinspect-2.0.0.tar.gz -o appinspect-lastest.tar.gz
#            tar -zxvf appinspect-lastest.tar.gz -C appinspect-latest --strip-components=1
      - run:
          name: install appinspect
          command: |
            mkdir appinspect-latest
            cd appinspect-latest
            rm -rf venv
            sudo pip install --upgrade pip setuptools
            sudo pip install virtualenv
            virtualenv --python=/usr/bin/python3 --clear venv
            source venv/bin/activate
            pip install splunk-appinspect -t . 
#            pip install .
#            cd appinspect-latest
      - run:
          name: run appinspect
          command: |
            rm -rf devtutorial/.git
            rm -rf devtutorial/.circleci
            rm -rf devtutorial/.gitignore
            tar -zcvf devtutorial.tar.gz devtutorial
            mkdir dist
            cp devtutorial.tar.gz dist/
            cd appinspect-latest
            source venv/bin/activate
            splunk-appinspect inspect ../devtutorial.tar.gz --included-tags=cloud 
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "devtutorial/default/app.conf" }}
          paths:
            - "venv"
      - store_artifacts:
          path: devtutorial.tar.gz
          destination: devtutorial-latest.tar.gz
      - persist_to_workspace:
          root: dist/
          paths:
              - devtutorial.tar.gz
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/dist/devtutorial.tar.gz
      - run:
          name: publish release on github
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ~/dist/devtutorial.tar.gz
workflows:
  version: 2.1
  validate-and-build:
    jobs:
      - validate-content:
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - validate-content
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
